import fs from 'node:fs';
import { session, sleep } from '<issue-to-pr-skill>/scripts/cdp/act.mjs';
import { canvas } from '<work>/wv.mjs';
const ROOT = process.env.DEMO;
let failed = 0;
const check = (n, ok, d = '') => { console.log(`${ok ? 'PASS' : 'FAIL'}  ${n}${ok ? '' : '  ' + d}`); if (!ok) failed++; };
const domain = () => JSON.parse(fs.readFileSync(`${ROOT}/.erd-studio/gold/orders.json`, 'utf-8')).logical.relationships;
const lib = (m) => fs.readFileSync(`${ROOT}/.erd-studio/logical-models/${m}.yml`, 'utf-8');
const c = await canvas({ marks: '/dev/null' });
await c.ev(`(() => { win.dispatchEvent(new win.CustomEvent('column-relationship-drop', { detail: { fromModel: 'dim_date', fromColumn: 'date_key', toModel: 'fct_order', toColumn: 'ship_date_key' } })); return 1; })()`);
await c.waitFor(`doc.querySelector('.new-fk-dialog')`); await sleep(400);
const readback = await c.ev(`(doc.querySelector('.new-fk-dialog__readback')||{}).textContent || ''`);
check('read-back says it is saved in this diagram', /diagram/i.test(readback) && !/fct_order\.yml/.test(readback), readback);
await c.ev(`(doc.querySelector('.new-fk-dialog__button--primary').click(), 1)`); await sleep(2500);
const rels = domain();
check('saved in the diagram file, many side first', rels.length === 2 && rels.some((r) => r.fromModel === 'fct_order' && r.fromColumn === 'ship_date_key' && r.toModel === 'dim_date' && r.cardinality === 'many-to-one'), JSON.stringify(rels));
check('no model file gained a relationships list', !/relationships:/.test(lib('fct_order') + lib('dim_date') + lib('dim_customer')));
check('two lines drawn', (await c.ev(`doc.querySelectorAll('.react-flow__edge').length`)) === 2);
c.close();
process.exit(failed ? 1 : 0);
