/**
 * SelectorsService — generates a single `selectors.yml` at the dbt project root
 * describing one named selector per ERD Studio domain.
 *
 * Why this instead of tagging model YAMLs:
 *   Adding `tags: [domain:foo]` to a model's schema.yml mutates that node's
 *   parsed hash, which dbt's `state:modified` comparator picks up. For a
 *   conformed dimension shared across many domains, this cascades through
 *   `state:modified+` and rebuilds every downstream model in CI.
 *
 *   `selectors.yml` lives at the project root and is NOT part of any model's
 *   node hash, so regenerating it never marks a model as modified. Users still
 *   refresh a domain with one command:
 *
 *     dbt build --selector domain_silver_customer_360
 *
 * Selector name format: `domain_{layer}_{domain}` with `-` replaced by `_`
 * to match dbt's snake_case convention.
 */

import * as fs from 'fs';
import * as path from 'path';
import { stringify as yamlStringify } from 'yaml';

import type { DomainService } from './domainService';

const SELECTORS_FILENAME = 'selectors.yml';
const HEADER = '# AUTOGENERATED by ERD Studio — do not edit by hand.\n# Regenerated whenever a domain is created, renamed, deleted, or its model list changes.\n';

interface SelectorDef {
  name: string;
  description: string;
  definition: {
    union: Array<{ method: 'fqn'; value: string }>;
  };
}

export interface RegenerateResult {
  selectorsWritten: number;
  modelsReferenced: number;
  filePath: string;
}

export class SelectorsService {
  private debounceTimer: ReturnType<typeof setTimeout> | undefined;

  constructor(
    private readonly domainService: DomainService,
    private readonly workspaceRoot: string,
    private readonly semanticDir: string,
  ) {}

  /**
   * Debounced regenerate — coalesces bursts of mutations (e.g. bulk add) into
   * one write. Safe to call from any mutation handler.
   */
  scheduleRegenerate(delayMs = 250): void {
    if (this.debounceTimer) {
      clearTimeout(this.debounceTimer);
    }
    this.debounceTimer = setTimeout(() => {
      this.debounceTimer = undefined;
      try {
        this.regenerate();
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        console.error(`[SelectorsService] Regenerate failed: ${msg}`);
      }
    }, delayMs);
  }

  /**
   * Read every domain file and write a fresh `selectors.yml` at the dbt
   * project root. Overwrites atomically — never partially updates the file.
   */
  regenerate(): RegenerateResult {
    const summaries = this.domainService.listDomains(this.workspaceRoot, this.semanticDir);

    const selectors: SelectorDef[] = [];
    let modelsReferenced = 0;

    // Stable ordering: layer then domain name
    const sorted = [...summaries].sort((a, b) =>
      a.layer === b.layer ? a.domain.localeCompare(b.domain) : a.layer.localeCompare(b.layer),
    );

    for (const summary of sorted) {
      let unified;
      try {
        unified = this.domainService.getDomain(summary.filePath);
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        console.warn(`[SelectorsService] Skipping ${summary.filePath}: ${msg}`);
        continue;
      }

      const models = unified.logical?.models ?? [];
      if (models.length === 0) {
        continue;
      }

      const seen = new Set<string>();
      const members: Array<{ method: 'fqn'; value: string }> = [];
      for (const model of models) {
        if (seen.has(model.name)) { continue; }
        seen.add(model.name);
        members.push({ method: 'fqn', value: model.name });
      }

      modelsReferenced += members.length;
      selectors.push({
        name: this.selectorName(summary.layer, summary.domain),
        description: `All models in the ${summary.domain} domain (${summary.layer} layer). Managed by ERD Studio.`,
        definition: { union: members },
      });
    }

    const filePath = path.join(this.workspaceRoot, SELECTORS_FILENAME);
    const yamlBody = yamlStringify({ selectors }, { lineWidth: 0 });
    const content = HEADER + yamlBody;

    this.atomicWrite(filePath, content);

    return {
      selectorsWritten: selectors.length,
      modelsReferenced,
      filePath,
    };
  }

  /**
   * Selector name format — dbt-friendly snake_case. dbt requires selector
   * names to be identifier-safe. Domain slugs are already validated at
   * creation time, but layer IDs come from user-editable layers.json and
   * may contain arbitrary characters (dots, spaces, slashes, etc.), so we
   * defensively replace anything non-alphanumeric with `_` and collapse/trim.
   */
  private selectorName(layer: string, domain: string): string {
    const sanitize = (s: string): string =>
      s
        .replace(/[^A-Za-z0-9]+/g, '_')
        .replace(/^_+|_+$/g, '')
        .toLowerCase();
    return `domain_${sanitize(layer)}_${sanitize(domain)}`;
  }

  /** Write via temp file + rename so a crash never leaves a partial selectors.yml. */
  private atomicWrite(filePath: string, content: string): void {
    const tmpPath = `${filePath}.tmp-${process.pid}`;
    fs.writeFileSync(tmpPath, content, 'utf-8');
    fs.renameSync(tmpPath, filePath);
  }
}
