/**
 * SelectorsService — generates a single `selectors.yml` at the dbt project root
 * describing one named selector per ERD Studio domain.
 *
 * Why this instead of tagging model YAMLs:
 *   Adding `tags: [domain:foo]` to a model's schema.yml mutates that node's
 *   parsed hash, which dbt's `state:modified` comparator picks up. For a
 *   conformed dimension shared across many domains, this cascades through
 *   `state:modified+` and rebuilds every downstream model in CI.
 *
 *   `selectors.yml` lives at the project root and is NOT part of any model's
 *   node hash, so regenerating it never marks a model as modified. Users still
 *   refresh a domain with one command:
 *
 *     dbt build --selector domain_silver_customer_360
 *
 * Selector name format: `domain_{layer}_{domain}` with `-` replaced by `_`
 * to match dbt's snake_case convention. A selector is recognised as ours
 * when its name starts with `domain_` AND its description carries the
 * `Managed by ERD Studio.` marker — any other selector (including a
 * user-authored `domain_*` one without the marker) is preserved across
 * regenerates (read-merge-write).
 *
 * Because sanitisation is lossy (`customer-360` and `customer_360` both map
 * to `customer_360`), generated names are de-duplicated against each other
 * and against preserved user selectors by appending `_2`, `_3`, ... dbt
 * itself silently lets the last duplicate win, so a collision would
 * otherwise build the wrong domain with no error.
 *
 * Skip-on-broken-state policy: when `selectors.yml` is malformed YAML, has no
 * `selectors:` key, has a non-list `selectors:` value, OR is currently open
 * in an editor with unsaved edits, the service refuses to write. It returns
 * a `'skipped'` result with a reason; the host (extension.ts) is expected to
 * surface a notification telling the user how to fix the issue and how to
 * trigger a resync. This is deliberately conservative — we'd rather drift
 * out-of-sync (recoverable, visible) than overwrite user work (irrecoverable).
 */

import * as fs from 'fs';
import * as path from 'path';
import { Document, parseDocument, isSeq, isMap } from 'yaml';
import type { YAMLMap, YAMLSeq, Node, Scalar } from 'yaml';

import type { DomainService } from './domainService';

const SELECTORS_FILENAME = 'selectors.yml';
const GENERATED_PREFIX = 'domain_';
/** Description suffix that marks a selector as generated by ERD Studio. */
const MANAGED_MARKER = 'Managed by ERD Studio.';
const HEADER_COMMENT =
  ' ERD Studio manages selectors prefixed with `domain_` whose description ends with "Managed by ERD Studio." — regenerated automatically.\n' +
  ' Other selectors below are user-managed and preserved across regenerates.';

interface SelectorDef {
  name: string;
  description: string;
  definition: {
    union: Array<{ method: 'fqn'; value: string }>;
  };
  /** `{layer}/{domain}` this selector was generated from (not written to YAML). */
  source: string;
}

export type SkipReason = 'malformed' | 'unsaved-edits';

export interface SkipInfo {
  reason: SkipReason;
  filePath: string;
  /** Human-readable detail (e.g. parse error message). Safe to put in a notification. */
  detail: string;
}

export type RegenerateResult =
  | { status: 'written'; selectorsWritten: number; modelsReferenced: number; filePath: string }
  | { status: 'skipped'; reason: SkipReason; filePath: string; detail: string }
  /** Nothing to write and no file on disk — the workspace was left untouched. */
  | { status: 'noop'; filePath: string };

export interface SelectorsServiceHooks {
  /**
   * Return true to refuse the write — used to skip when the file has unsaved
   * edits in an open editor. Receives the absolute path of `selectors.yml`.
   */
  isFileDirtyInEditor?: (filePath: string) => boolean;
  /**
   * Called when regenerate skipped a write because of unsaved edits or a
   * malformed file. Surface a notification, status bar item, etc.
   */
  onSkipped?: (info: SkipInfo) => void;
  /**
   * Called when a regenerate successfully wrote the file. Used to clear any
   * "out of sync" status bar item the host may have shown.
   */
  onWritten?: () => void;
  /**
   * Called when two domains sanitise to the same selector name (or a
   * generated name collides with a user-managed selector). The write still
   * happens with a `_2`/`_3` suffix; surface this so the user can rename.
   */
  onNameCollision?: (info: NameCollisionInfo) => void;
}

export interface NameCollisionInfo {
  /** The selector name that was already taken. */
  requestedName: string;
  /** The suffixed name that was written instead. */
  assignedName: string;
  /** `{layer}/{domain}` of the domain that received the suffixed name. */
  domain: string;
  /** Who owns `requestedName`: another domain (`{layer}/{domain}`) or a user selector. */
  conflictsWith: string;
}

type LoadOk = { status: 'ok'; doc: Document; preservedItems: Node[]; preservedNames: string[] };
type LoadMalformed = { status: 'malformed'; detail: string };
type LoadResult = LoadOk | LoadMalformed;

export class SelectorsService {
  private debounceTimer: ReturnType<typeof setTimeout> | undefined;

  constructor(
    private readonly domainService: DomainService,
    private readonly workspaceRoot: string,
    private readonly semanticDir: string,
    private readonly hooks?: SelectorsServiceHooks,
  ) {}

  /**
   * Debounced regenerate — coalesces bursts of mutations (e.g. bulk add) into
   * one write. Safe to call from any mutation handler.
   */
  scheduleRegenerate(delayMs = 250): void {
    if (this.debounceTimer) {
      clearTimeout(this.debounceTimer);
    }
    this.debounceTimer = setTimeout(() => {
      this.debounceTimer = undefined;
      try {
        this.regenerate();
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        console.error(`[SelectorsService] Regenerate failed: ${msg}`);
      }
    }, delayMs);
  }

  /**
   * Read every domain file, merge with any user-managed selectors already in
   * `selectors.yml`, and write a fresh file at the dbt project root.
   *
   * Selectors with names starting with `domain_` are owned by ERD Studio and
   * fully replaced on each regenerate (so renamed/deleted domains don't
   * leave stale entries). Selectors with any other name are preserved as
   * AST nodes — comments and formatting round-trip across regenerates.
   *
   * Returns a discriminated union:
   *   - `'written'`: file was rewritten. Includes counts.
   *   - `'skipped'`: file was NOT touched. Includes reason and detail. The
   *     host should surface a notification telling the user what to fix and
   *     offering a re-sync action.
   *   - `'noop'`: there are no domains with models AND `selectors.yml` does
   *     not exist. Nothing is written so merely opening a dbt repo with the
   *     extension installed never dirties its git status. (An existing file
   *     is still regenerated so stale `domain_*` selectors get removed.)
   *
   * Skip conditions (any of these):
   *   - `selectors.yml` is open in an editor with unsaved edits
   *     (detected via `hooks.isFileDirtyInEditor`).
   *   - `parseDocument` reports any error (malformed YAML).
   *   - `selectors:` key is missing or its value isn't a list.
   */
  regenerate(): RegenerateResult {
    const filePath = path.join(this.workspaceRoot, SELECTORS_FILENAME);

    // Skip #1: open with unsaved edits.
    if (this.hooks?.isFileDirtyInEditor?.(filePath)) {
      const result: RegenerateResult = {
        status: 'skipped',
        reason: 'unsaved-edits',
        filePath,
        detail: 'File has unsaved edits in an open editor.',
      };
      this.hooks.onSkipped?.(result);
      return result;
    }

    const summaries = this.domainService.listDomains(this.workspaceRoot, this.semanticDir);

    const generated: SelectorDef[] = [];
    let modelsReferenced = 0;

    // Stable ordering: layer then domain name
    const sorted = [...summaries].sort((a, b) =>
      a.layer === b.layer ? a.domain.localeCompare(b.domain) : a.layer.localeCompare(b.layer),
    );

    for (const summary of sorted) {
      let unified;
      try {
        unified = this.domainService.getDomain(summary.filePath);
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        console.warn(`[SelectorsService] Skipping ${summary.filePath}: ${msg}`);
        continue;
      }

      const models = unified.logical?.models ?? [];
      if (models.length === 0) {
        continue;
      }

      const seen = new Set<string>();
      const members: Array<{ method: 'fqn'; value: string }> = [];
      for (const model of models) {
        if (seen.has(model.name)) { continue; }
        seen.add(model.name);
        members.push({ method: 'fqn', value: model.name });
      }

      modelsReferenced += members.length;
      generated.push({
        name: this.selectorName(summary.layer, summary.domain),
        description: `All models in the ${summary.domain} domain (${summary.layer} layer). ${MANAGED_MARKER}`,
        definition: { union: members },
        source: `${summary.layer}/${summary.domain}`,
      });
    }

    // Nothing to write and nothing on disk: leave the workspace untouched.
    if (generated.length === 0 && !fs.existsSync(filePath)) {
      return { status: 'noop', filePath };
    }

    const loaded = this.loadDocAndExtractUserItems(filePath);

    // Skip #2: malformed file.
    if (loaded.status === 'malformed') {
      const result: RegenerateResult = {
        status: 'skipped',
        reason: 'malformed',
        filePath,
        detail: loaded.detail,
      };
      this.hooks?.onSkipped?.(result);
      return result;
    }

    const { doc, preservedItems, preservedNames } = loaded;

    this.dedupeSelectorNames(generated, preservedNames);

    // Replace the selectors seq's items with [generated, ...preservedItems].
    // Mutating the same doc keeps anchor/alias references resolvable.
    const seq = doc.get('selectors') as YAMLSeq;
    seq.items.length = 0;
    seq.flow = false;
    // Any leading comment was promoted onto a specific item during extraction,
    // so the seq itself should no longer carry it (else it would re-attach
    // above the first generated selector on the next round-trip).
    seq.commentBefore = null;
    for (const gen of generated) {
      const { source: _source, ...selector } = gen;
      seq.add(doc.createNode(selector));
    }
    for (const item of preservedItems) {
      seq.add(item);
    }

    // The whole region above `selectors:` is ERD-Studio-owned. The yaml lib
    // parks comments differently depending on whitespace: a header written
    // without a trailing blank line attaches to the `selectors:` key node,
    // not to the document. Wipe every slot above the seq so HEADER_COMMENT
    // is the only thing that survives there.
    const root = doc.contents;
    if (root && isMap(root)) {
      (root as YAMLMap).commentBefore = null;
      for (const pair of (root as YAMLMap).items) {
        const keyValue = (pair.key as Scalar | undefined)?.value;
        if (keyValue !== 'selectors') { continue; }
        if (pair.key && typeof pair.key === 'object') {
          (pair.key as Scalar).commentBefore = null;
        }
        break;
      }
    }
    doc.commentBefore = HEADER_COMMENT;

    const content = doc.toString({ lineWidth: 0 });
    this.atomicWrite(filePath, content);

    this.hooks?.onWritten?.();

    return {
      status: 'written',
      selectorsWritten: generated.length,
      modelsReferenced,
      filePath,
    };
  }

  /**
   * Ensure every generated selector name is unique — both among the
   * generated set and against user-managed selectors that are preserved.
   * Lossy sanitisation means `customer-360` and `customer_360` collide;
   * the later (sorted) domain gets a `_2`, `_3`, ... suffix and the host
   * is notified via `hooks.onNameCollision`.
   */
  private dedupeSelectorNames(generated: SelectorDef[], preservedNames: string[]): void {
    const owners = new Map<string, string>();
    for (const name of preservedNames) {
      owners.set(name, 'a user-managed selector');
    }
    for (const gen of generated) {
      const requested = gen.name;
      if (!owners.has(requested)) {
        owners.set(requested, gen.source);
        continue;
      }
      let suffix = 2;
      while (owners.has(`${requested}_${suffix}`)) {
        suffix++;
      }
      const assigned = `${requested}_${suffix}`;
      const conflictsWith = owners.get(requested) ?? 'unknown';
      owners.set(assigned, gen.source);
      gen.name = assigned;
      console.warn(
        `[SelectorsService] Selector name "${requested}" for domain ${gen.source} collides with ` +
        `${conflictsWith}; wrote "${assigned}" instead.`,
      );
      this.hooks?.onNameCollision?.({ requestedName: requested, assignedName: assigned, domain: gen.source, conflictsWith });
    }
  }

  /**
   * Parse the existing `selectors.yml` and return either:
   *   - `{ status: 'ok', doc, preservedItems, preservedNames }` — clean parse
   *     with usable selectors seq. `preservedItems` are the AST nodes for
   *     every user-managed selector (anything not carrying both the
   *     `domain_` prefix and the `Managed by ERD Studio.` description marker);
   *     `preservedNames` are their `name` values.
   *   - `{ status: 'malformed', detail }` — anything else: parse error,
   *     missing `selectors:` key, or non-list `selectors:` value.
   *
   * No file → fresh empty doc, `preservedItems: []`. Empty file → same.
   */
  private loadDocAndExtractUserItems(filePath: string): LoadResult {
    let raw: string;
    try {
      raw = fs.readFileSync(filePath, 'utf-8');
    } catch (err) {
      if ((err as NodeJS.ErrnoException).code === 'ENOENT') {
        return { status: 'ok', doc: new Document({ selectors: [] }), preservedItems: [], preservedNames: [] };
      }
      throw err;
    }

    if (raw.trim() === '') {
      return { status: 'ok', doc: new Document({ selectors: [] }), preservedItems: [], preservedNames: [] };
    }

    const doc = parseDocument(raw);
    if (doc.errors.length > 0) {
      return { status: 'malformed', detail: doc.errors[0].message };
    }

    const selectorsNode = doc.get('selectors');
    if (selectorsNode === undefined || selectorsNode === null) {
      return { status: 'malformed', detail: 'No top-level `selectors:` key found.' };
    }
    if (!isSeq(selectorsNode)) {
      return { status: 'malformed', detail: '`selectors:` value is not a list.' };
    }

    const seq = selectorsNode as YAMLSeq;

    // The yaml lib stores a comment that appears immediately before the FIRST
    // seq item on the seq itself (`seq.commentBefore`), not on the item.
    // Promote it onto the first item so the comment-to-item binding survives
    // filtering and re-emission. Comments between subsequent items already
    // live on the *next* item's `commentBefore`, which round-trips naturally.
    if (seq.commentBefore && seq.items.length > 0) {
      const firstItem = seq.items[0] as Node | undefined;
      if (firstItem && typeof firstItem === 'object') {
        const existing = firstItem.commentBefore;
        firstItem.commentBefore = existing
          ? `${seq.commentBefore}\n${existing}`
          : seq.commentBefore;
      }
    }

    const preserved: Node[] = [];
    const preservedNames: string[] = [];
    for (const item of seq.items) {
      // Non-map items (bare strings, numbers, etc.) cannot be ours by shape
      // — preserve verbatim. Better to keep something we don't understand
      // than to delete user data.
      if (!isMap(item)) {
        preserved.push(item as Node);
        continue;
      }
      const map = item as YAMLMap;
      const nameNode = map.get('name', true) as Scalar | undefined;
      const nameValue = nameNode?.value;
      const nameStr = typeof nameValue === 'string' ? nameValue : '';
      const descNode = map.get('description', true) as Scalar | undefined;
      const descValue = descNode?.value;
      const descStr = typeof descValue === 'string' ? descValue : '';
      // Ours only when BOTH the prefix and the description marker match.
      // Missing/non-string `name`, or a user-authored `domain_*` selector
      // without the marker → cannot be ours → preserve.
      const isOurs = nameStr.startsWith(GENERATED_PREFIX) && descStr.includes(MANAGED_MARKER);
      if (!isOurs) {
        preserved.push(item as Node);
        if (nameStr) {
          preservedNames.push(nameStr);
        }
      }
    }

    return { status: 'ok', doc, preservedItems: preserved, preservedNames };
  }

  /**
   * Selector name format — dbt-friendly snake_case. dbt requires selector
   * names to be identifier-safe. Domain slugs are already validated at
   * creation time, but layer IDs come from user-editable layers.json and
   * may contain arbitrary characters (dots, spaces, slashes, etc.), so we
   * defensively replace anything non-alphanumeric with `_` and collapse/trim.
   */
  private selectorName(layer: string, domain: string): string {
    const sanitize = (s: string): string =>
      s
        .replace(/[^A-Za-z0-9]+/g, '_')
        .replace(/^_+|_+$/g, '')
        .toLowerCase();
    return `domain_${sanitize(layer)}_${sanitize(domain)}`;
  }

  /** Write via temp file + rename so a crash never leaves a partial selectors.yml. */
  private atomicWrite(filePath: string, content: string): void {
    const tmpPath = `${filePath}.tmp-${process.pid}`;
    fs.writeFileSync(tmpPath, content, 'utf-8');
    fs.renameSync(tmpPath, filePath);
  }
}
