/**
 * loadDisplayDomain against the extension host's golden output.
 *
 * The golden files (test/fixtures/golden) are generated by the repo-root test
 * test/unit/displayDomainGolden.test.ts, which drives the real extension host
 * over the same fixture projects. This proves the one-call core pipeline
 * builds the same DisplayDomain the extension posts to its webview — minus
 * the editor-only `templates`, `manifestModels` and `existingModels` — and
 * fails bad domains with the same messages.
 *
 * Domain paths are passed relative to each fixture project, the way a host
 * reading from a repository would name them, so the golden messages are
 * compared with their `<root>/` prefix removed.
 */

import { describe, it, expect } from 'vitest';
import * as fs from 'fs';
import * as path from 'path';

import { loadDisplayDomain } from '../../src/loadDisplayDomain';
import { DomainFileError, DomainValidationError } from '../../src/domain';

const FIXTURES = path.resolve(__dirname, '../fixtures');
const GOLDEN_DIR = path.join(FIXTURES, 'golden');

const DOMAIN_CASES: Record<string, string> = {
  showcase: '.erd-studio/silver/showcase.json',
  'v4-inline': '.erd-studio/bronze/orders.json',
  'missing-model': '.erd-studio/silver/partial.json',
  'no-layers': '.erd-studio/gold/accounts.json',
  'missing-positions': '.erd-studio/silver/showcase.json',
};

const ERROR_CASES: Record<string, string> = {
  legacy: '.erd-studio/silver/legacy.json',
  hybrid: '.erd-studio/silver/hybrid.json',
  future: '.erd-studio/silver/future.json',
  noversion: '.erd-studio/silver/noversion.json',
  array: '.erd-studio/silver/array.json',
  empty: '.erd-studio/silver/empty.json',
  invalid: '.erd-studio/silver/invalid.json',
  badlayer: '.erd-studio/platinum/badlayer.json',
};

const LINE_COLUMN = / \(line \d+ column \d+\)/g;

function readGolden(file: string): { type: string; payload: Record<string, unknown> } {
  return JSON.parse(fs.readFileSync(path.join(GOLDEN_DIR, file), 'utf-8'));
}

/** A readFile over one fixture project: relative paths, ENOENT as null. */
function fsReadFile(root: string) {
  return async (p: string): Promise<string | null> => {
    try {
      return fs.readFileSync(path.join(root, p), 'utf-8');
    } catch (err) {
      if ((err as NodeJS.ErrnoException).code === 'ENOENT') return null;
      throw err;
    }
  };
}

describe('loadDisplayDomain matches the extension host golden output', () => {
  describe.each(Object.entries(DOMAIN_CASES))('%s', (name, domainPath) => {
    it('builds the posted DisplayDomain, without the editor-only fields', async () => {
      const root = path.join(FIXTURES, name);
      const domain = await loadDisplayDomain({
        domainPath,
        readFile: fsReadFile(root),
        readOnly: false,
        warn: () => {},
      });

      const expected = { ...readGolden(`${name}.host.json`).payload };
      delete expected.templates;
      delete expected.manifestModels;
      delete expected.existingModels;

      // postMessage serialises the payload, which drops undefined values.
      expect(JSON.parse(JSON.stringify(domain))).toEqual(expected);
    });
  });

  describe.each(Object.entries(ERROR_CASES))('errors/%s', (name, domainPath) => {
    it('rejects with the golden message and the matching error class', async () => {
      const golden = readGolden(`errors.${name}.host.json`).payload as { message: string; kind?: string };
      let caught: unknown;
      try {
        await loadDisplayDomain({
          domainPath,
          readFile: fsReadFile(path.join(FIXTURES, 'errors')),
          readOnly: false,
          warn: () => {},
        });
      } catch (err) {
        caught = err;
      }
      // The host tags DomainFileError failures with kind 'domain-file'.
      expect(caught).toBeInstanceOf(golden.kind === 'domain-file' ? DomainFileError : DomainValidationError);
      const message = (caught as Error).message.replace(LINE_COLUMN, '');
      expect(message).toBe(golden.message.split('<root>/').join(''));
    });
  });
});
