/**
 * Shared feedback types — the contract between the Feedback dialog (webview),
 * the feedback services (extension host) and the GitHub issue forms.
 *
 * This module is imported by BOTH tsconfigs and by the mcp-server type-check,
 * so it must stay free of `vscode` and of DOM types. The pure helpers at the
 * bottom (readiness scoring, version compare, duplicate mode, footer routing)
 * live here rather than in a service because the webview needs them too and
 * cannot import anything that touches `vscode`.
 */

// ---------------------------------------------------------------------------
// Kind
// ---------------------------------------------------------------------------

/** What the user is filing. Drives the issue template, copy and field ids. */
export type FeedbackKind = 'bug' | 'feature';

export const FEEDBACK_KINDS: readonly FeedbackKind[] = ['bug', 'feature'];

// ---------------------------------------------------------------------------
// Dialog copy
// ---------------------------------------------------------------------------

/** The per-kind strings the dialog swaps when the kind changes. */
export interface FeedbackKindCopy {
  head: string;
  descLabel: string;
  contextLabel: string;
  contextPlaceholder: string;
  verdict: string;
  template: string;
}

/** Dialog title before the analysis has decided on a kind. */
export const FEEDBACK_PRE_ANALYSIS_TITLE = 'Send feedback';

/**
 * Frozen dialog copy. Lives here (not in the component) so the webview and the
 * tests read the same literals instead of hard-coding them twice.
 */
export const FEEDBACK_COPY: Readonly<Record<FeedbackKind, FeedbackKindCopy>> = {
  bug: {
    head: 'Report a bug',
    descLabel: 'Tell us what happened',
    contextLabel: 'Steps to reproduce',
    contextPlaceholder: '1. Open silver/orders\n2. …',
    verdict: 'Bug',
    template: 'bug_report.yml',
  },
  feature: {
    head: 'Request a feature',
    descLabel: 'What would you like to be able to do?',
    contextLabel: 'Why do you want it?',
    contextPlaceholder: 'Today I work around this by…',
    verdict: 'Feature request',
    template: 'feature_request.yml',
  },
};

// ---------------------------------------------------------------------------
// Attachments
// ---------------------------------------------------------------------------

/** Image types GitHub accepts and the dialog will take. */
export type FeedbackImageMime = 'image/png' | 'image/jpeg' | 'image/gif' | 'image/webp';

export const FEEDBACK_IMAGE_MIMES: readonly FeedbackImageMime[] = [
  'image/png',
  'image/jpeg',
  'image/gif',
  'image/webp',
];

/** File extension written to disk for each accepted mime type. */
export const FEEDBACK_MIME_EXTENSIONS: Readonly<Record<FeedbackImageMime, string>> = {
  'image/png': '.png',
  'image/jpeg': '.jpg',
  'image/gif': '.gif',
  'image/webp': '.webp',
};

/** How an attachment entered the dialog. `canvas` is the auto-captured screenshot. */
export type FeedbackAttachmentSource = 'canvas' | 'picker' | 'paste' | 'drop';

export const FEEDBACK_ATTACHMENT_SOURCES: readonly FeedbackAttachmentSource[] = [
  'canvas',
  'picker',
  'paste',
  'drop',
];

/** Maximum number of images on one report. */
export const MAX_ATTACHMENTS = 4;

/** Maximum decoded size of a single image (10 MB). */
export const MAX_ATTACHMENT_BYTES = 10 * 1024 * 1024;

/**
 * Aggregate ceiling across all attachments in one `submitFeedback` message.
 * Deliberately the per-image limit times the image count, so a report that
 * passes every per-image check can never fail on the aggregate afterwards.
 * postMessage carries base64, so the wire cost is ~4/3 of this.
 */
export const MAX_TOTAL_ATTACHMENT_BYTES = MAX_ATTACHMENTS * MAX_ATTACHMENT_BYTES;

/** One image on a report. `dataUrl` is `data:<mime>;base64,<payload>`. */
export interface FeedbackAttachment {
  /** Stable for the lifetime of the dialog; generated by the webview. */
  id: string;
  /** Original file name, or `canvas.png` for the captured canvas. */
  name: string;
  mime: FeedbackImageMime;
  /** Decoded byte length (not the base64 length). */
  bytes: number;
  dataUrl: string;
  source: FeedbackAttachmentSource;
  /** True when the webview managed to place this image on the clipboard. */
  onClipboard?: boolean;
}

// ---------------------------------------------------------------------------
// Draft
// ---------------------------------------------------------------------------

/**
 * What the user has in the dialog when they press the primary button.
 *
 * Structurally a superset of `BugReportDraft` in feedbackService.ts, so it can
 * be passed straight to `composeIssueFields()`. `steps` carries the context
 * field for BOTH kinds (steps to reproduce for `bug`, rationale for `feature`);
 * `composeFeedbackFields()` maps it to the right issue-form field id.
 */
export interface FeedbackDraft {
  kind: FeedbackKind;
  title: string;
  description: string;
  /** Steps to reproduce (bug) or rationale (feature). */
  steps?: string;
  includeDiagnostics: boolean;
  attachments?: FeedbackAttachment[];
  /** Legacy single-screenshot fields — kept so this stays a BugReportDraft. */
  screenshotDataUrl?: string;
  screenshotOnClipboard?: boolean;
  /** Why the canvas capture failed, when the user asked for one. */
  screenshotError?: string;
  /** Recent errors observed by the webview (oldest → newest). */
  webviewErrors?: string[];
  /** Filing fresh against an issue that was closed as fixed — title gets "Regression: ". */
  regressionOf?: number;
  /** Post the description as a comment on this issue instead of filing anything new. */
  commentOnIssue?: number;
}

// ---------------------------------------------------------------------------
// Diagnostics (webview-facing view of the host's Diagnostics)
// ---------------------------------------------------------------------------

/** One diagnostics chip rendered in the dialog. */
export interface FeedbackDiagnosticsChip {
  label: string;
  tone: 'normal' | 'error';
}

/**
 * What the host pushes to the dialog so it can show chips and the exact text
 * without ever reconstructing diagnostics in the webview.
 */
export interface FeedbackDiagnosticsView {
  chips: FeedbackDiagnosticsChip[];
  /** Verbatim `formatDiagnostics()` output, shown in the `<details><pre>`. */
  text: string;
}

/** Capability snapshot pushed alongside the diagnostics view. */
export interface FeedbackCapabilities {
  /** Running extension version, e.g. "0.6.49". */
  extensionVersion: string;
  /** True when at least one AI tier is configured AND `feedback.aiAssist` is on. */
  aiAvailable: boolean;
  /** Human label for the configured tier, e.g. "Copilot" or "api.example.com". Null when unavailable. */
  aiProviderLabel: string | null;
  /** GitHub handle from a silent session, or null. Never triggers a sign-in prompt. */
  githubHandle: string | null;
  /** True when a canvas is behind the dialog and a screenshot can be captured. */
  canCaptureCanvas: boolean;
}

// ---------------------------------------------------------------------------
// Analysis
// ---------------------------------------------------------------------------

/** Which takeover UI a strong duplicate gets. Derived from GitHub state + state_reason. */
export type DuplicateMode = 'open' | 'fixed' | 'declined';

export const DUPLICATE_MODES: readonly DuplicateMode[] = ['open', 'fixed', 'declined'];

/**
 * A ranked existing issue that might already cover this report.
 *
 * Only `number`, `match` and `why` ever come from the model — every other
 * field is hydrated from the issue list the host fetched, because a
 * hallucinated `stateReason` / `fixedIn` would tell a user to update for a bug
 * that is still open.
 */
export interface DuplicateCandidate {
  number: number;
  title: string;
  /** 0..1 confidence that this is the same thing. */
  match: number;
  /** One sentence from the model on why it matched. */
  why: string;
  state: 'open' | 'closed';
  /** Mirrors GitHub's `issue.state_reason`. Absent while open. */
  stateReason?: 'completed' | 'not_planned';
  comments?: number;
  /** True when the issue has an assignee ("being worked on"). */
  assigned?: boolean;
  /** Version the fix shipped in, for `fixed` mode. */
  fixedIn?: string;
  /** Maintainer's closing reasoning, for `declined` mode. */
  closingNote?: string;
  url: string;
}

/** Model-supplied prose for the unmet readiness checks. Never scores. */
export interface FeedbackAnalysisReasons {
  desc?: string | null;
  ctx?: string | null;
  image?: string | null;
}

/** The single AI call's whole result. Every field is a suggestion, never a decision. */
export interface FeedbackAnalysis {
  kind: FeedbackKind;
  /** 0..1. */
  confidence: number;
  /** Suggested issue title. */
  title: string;
  /** Extracted steps to reproduce (bug) or rationale (feature). */
  context: string;
  reasons: FeedbackAnalysisReasons;
  /** Ranked, highest `match` first. */
  duplicates: DuplicateCandidate[];
}

// ---------------------------------------------------------------------------
// Thresholds & readiness weights
// ---------------------------------------------------------------------------

/** At or above this match, the duplicate takes the dialog over. */
export const DUPLICATE_TAKEOVER_THRESHOLD = 0.7;

/** At or above this (and below takeover), the duplicate is a quiet "Possibly related" row. */
export const DUPLICATE_RELATED_THRESHOLD = 0.3;

/** Debounce before re-running the analysis after a description edit. */
export const ANALYSIS_DEBOUNCE_MS = 850;

/** Below this description length the dialog never calls the model. */
export const MIN_DESCRIPTION_CHARS = 12;

/** Point weights for the readiness meter. They sum to 100. */
export const READINESS_WEIGHTS = {
  description: 40,
  /** Partial credit for a description between THIN and CLEAR. */
  descriptionThin: 22,
  context: 30,
  attachment: 20,
  diagnostics: 10,
} as const;

/** Denominator for the readiness percentage. */
export const READINESS_MAX =
  READINESS_WEIGHTS.description +
  READINESS_WEIGHTS.context +
  READINESS_WEIGHTS.attachment +
  READINESS_WEIGHTS.diagnostics;

/** Description length that earns full marks. */
export const DESCRIPTION_CLEAR_CHARS = 90;

/** Description length that earns partial marks. */
export const DESCRIPTION_THIN_CHARS = 40;

/** Context (steps/rationale) must be strictly longer than this to count. */
export const CONTEXT_MIN_CHARS = 8;

/** Percentage at which the readiness bar turns green. */
export const READINESS_GOOD_PCT = 70;

/** Which UI element a failed check's jump-to action focuses. */
export type ReadinessTarget = 'description' | 'context' | 'attachments' | 'diagnostics';

/** One row under the readiness bar. */
export interface ReadinessCheck {
  ok: boolean;
  label: string;
  /** Model-supplied prose, or a local fallback. Only on unmet checks. */
  why?: string | null;
  /** Action label, e.g. "Add them". Only on unmet checks that can be fixed in the dialog. */
  act?: string;
  target?: ReadinessTarget;
}

export interface ReadinessResult {
  /** 0..100, rounded. */
  score: number;
  checks: ReadinessCheck[];
}

/** Inputs to the readiness meter. All lengths are of already-trimmed text. */
export interface ReadinessInput {
  kind: FeedbackKind;
  descriptionLength: number;
  contextLength: number;
  attachmentCount: number;
  includeDiagnostics: boolean;
  reasons?: FeedbackAnalysisReasons;
}

// ---------------------------------------------------------------------------
// Tracking
// ---------------------------------------------------------------------------

/** One issue the user filed, as tracked in the "My Reports" view. */
export interface TrackedReport {
  number: number;
  title: string;
  url: string;
  kind: FeedbackKind;
  state: 'open' | 'closed';
  stateReason?: 'completed' | 'not_planned';
  comments: number;
  /**
   * Version the fix shipped in, when known. Read from the issue's milestone
   * title or a `shipped-in:<version>` label — never guessed.
   */
  shippedIn?: string;
  /** ISO timestamps from the GitHub API. */
  createdAt: string;
  updatedAt: string;
  /** True once the "shipped in vX" notification has been shown. */
  notifiedShipped?: boolean;
}

/** A submission the extension opened in the browser but has not yet reconciled. */
export interface PendingReport {
  title: string;
  kind: FeedbackKind;
  /** Epoch ms when the browser was opened; issues created after this are candidates. */
  openedAt: number;
}

/** Shape persisted in `globalState` under `TRACKED_REPORTS_KEY`. */
export interface TrackedReportsCache {
  handle: string;
  /** Epoch ms of the last successful poll. */
  fetchedAt: number;
  reports: TrackedReport[];
  pending: PendingReport[];
}

/** How often the tracker re-polls GitHub (6 hours). */
export const TRACKING_REFRESH_MS = 6 * 60 * 60 * 1000;

/** How long an unreconciled pending report is kept before it is dropped (7 days). */
export const TRACKING_PENDING_TTL_MS = 7 * 24 * 60 * 60 * 1000;

// ---------------------------------------------------------------------------
// Footer routing
// ---------------------------------------------------------------------------

/** Everything the footer's label and route line depend on. */
export interface FooterRouteInput {
  duplicate: { number: number; mode: DuplicateMode; fixedIn?: string } | null;
  filingAnyway: boolean;
  attachmentCount: number;
  version: string;
  outdated: boolean;
  /**
   * For a `fixed` duplicate: whether the comparison could be made at all.
   *
   * GitHub only tells us the version a fix shipped in when the issue carries a
   * milestone or a `shipped-in:` label, so most closed issues leave it unknown.
   * `false` means "we could not compare" — neither `outdated` nor "you already
   * have the fix" may then be asserted. Defaults to true so the two frozen
   * `fixed` rows are unchanged.
   */
  versionKnown?: boolean;
}

/** The footer's primary button label and its two-part explanation line. */
export interface FooterRoute {
  primaryLabel: string;
  /** Bolded lead-in, then the rest. Kept as two strings so no markup lives in a string. */
  lead: string;
  rest: string;
}

// ---------------------------------------------------------------------------
// Pure helpers (shared by host and webview)
// ---------------------------------------------------------------------------

/** True when `value` is one of the two feedback kinds. */
export function isFeedbackKind(value: unknown): value is FeedbackKind {
  return typeof value === 'string' && (FEEDBACK_KINDS as readonly string[]).includes(value);
}

/** The opposite kind, for the "Not right? Make it a …" flip link. */
export function otherKind(kind: FeedbackKind): FeedbackKind {
  return kind === 'bug' ? 'feature' : 'bug';
}

/**
 * Compare two dotted numeric versions. Returns <0 when `a` is older than `b`,
 * 0 when equal, >0 when newer. Missing segments count as 0; non-numeric
 * segments count as 0 ("0.6.44-beta" compares as "0.6.44").
 */
export function compareVersions(a: string, b: string): number {
  const parse = (v: string): number[] =>
    String(v)
      .split('.')
      .map((part) => {
        const n = parseInt(part, 10);
        return Number.isFinite(n) ? n : 0;
      });
  const left = parse(a);
  const right = parse(b);
  const length = Math.max(left.length, right.length);
  for (let i = 0; i < length; i++) {
    const diff = (left[i] ?? 0) - (right[i] ?? 0);
    if (diff !== 0) return diff < 0 ? -1 : 1;
  }
  return 0;
}

/** True when the running version is older than the version a fix shipped in. */
export function isVersionOlder(running: string, fixedIn: string): boolean {
  return compareVersions(running, fixedIn) < 0;
}

/** Which takeover a duplicate gets. `closed` without a reason is treated as `fixed`. */
export function duplicateModeFor(candidate: DuplicateCandidate): DuplicateMode {
  if (candidate.state === 'open') return 'open';
  return candidate.stateReason === 'not_planned' ? 'declined' : 'fixed';
}

/**
 * The single duplicate that takes the dialog over, or null. Only a candidate at
 * or above {@link DUPLICATE_TAKEOVER_THRESHOLD} qualifies; ties break on the
 * lower issue number (the older thread).
 */
export function pickTakeoverDuplicate(
  duplicates: readonly DuplicateCandidate[],
): DuplicateCandidate | null {
  let best: DuplicateCandidate | null = null;
  for (const candidate of duplicates) {
    if (candidate.match < DUPLICATE_TAKEOVER_THRESHOLD) continue;
    if (
      !best ||
      candidate.match > best.match ||
      (candidate.match === best.match && candidate.number < best.number)
    ) {
      best = candidate;
    }
  }
  return best;
}

/** The quiet "Possibly related" list: below takeover, at or above related. */
export function relatedDuplicates(
  duplicates: readonly DuplicateCandidate[],
): DuplicateCandidate[] {
  return duplicates
    .filter((d) => d.match >= DUPLICATE_RELATED_THRESHOLD && d.match < DUPLICATE_TAKEOVER_THRESHOLD)
    .sort((a, b) => b.match - a.match);
}

/** Prefix a title for a regression report, idempotently. */
export function applyRegressionPrefix(title: string): string {
  const trimmed = title.trim();
  return /^regression:\s/i.test(trimmed) ? trimmed : `Regression: ${trimmed}`;
}

/**
 * The inverse of {@link applyRegressionPrefix}, for when the regression claim
 * it was applied for is withdrawn — the analysis moved on to a different
 * duplicate, or to none. Removes one prefix only, so a title that genuinely
 * begins "Regression: Regression: …" is not silently rewritten twice.
 */
export function stripRegressionPrefix(title: string): string {
  return title.trim().replace(/^regression:\s+/i, '');
}

/**
 * The footer's primary label and route line.
 *
 * A strong duplicate owns the footer until the user chooses to file anyway;
 * otherwise the line explains how the images reach GitHub, because that hand-off
 * is the only part of the flow the user has to finish by hand.
 */
export function footerRoute(input: FooterRouteInput): FooterRoute {
  const { duplicate, filingAnyway, attachmentCount, version, outdated } = input;
  const versionKnown = input.versionKnown !== false;

  if (duplicate && !filingAnyway) {
    const number = duplicate.number;
    if (duplicate.mode === 'open') {
      return {
        primaryLabel: `Add to #${number}`,
        lead: 'Nothing new gets filed.',
        rest: ` Your description is posted as a comment on #${number}.`,
      };
    }
    if (duplicate.mode === 'declined') {
      return {
        primaryLabel: `Open #${number}`,
        lead: 'Closed as not planned.',
        rest: ' Read the reasoning first — reopening that thread beats a second issue.',
      };
    }
    // 'fixed'
    if (outdated) {
      return {
        primaryLabel: 'Update ERD Studio',
        lead: `Already fixed in ${duplicate.fixedIn ?? 'a newer version'}.`,
        rest: ` Updating is quicker than filing — you're on ${version}.`,
      };
    }
    // Closed as done, but nothing records which release carried the fix. Say
    // that, rather than claiming the user has it — calling this a regression
    // puts an unverifiable claim in the tracker, and telling them to update
    // could talk someone out of a real report.
    if (!versionKnown) {
      return {
        primaryLabel: 'File it anyway',
        lead: 'Closed as fixed.',
        rest: ` Update first; if it still happens, file it referencing #${number}.`,
      };
    }
    return {
      primaryLabel: 'Report as a regression',
      lead: 'You already have the fix,',
      rest: ` so this is a regression — worth its own issue, referencing #${number}.`,
    };
  }

  if (attachmentCount === 1) {
    return {
      primaryLabel: 'Open GitHub issue',
      lead: 'Opens GitHub.',
      rest: ' Your image goes on the clipboard — paste it into the Screenshot box.',
    };
  }
  if (attachmentCount > 1) {
    return {
      primaryLabel: 'Open GitHub issue',
      lead: 'Opens GitHub.',
      rest: ` The first of ${attachmentCount} images goes on the clipboard; the rest are saved to a folder you can reveal.`,
    };
  }
  return {
    primaryLabel: 'Open GitHub issue',
    lead: 'Opens the prefilled form.',
    rest: ' You review it and press Submit on GitHub — nothing is sent from VS Code.',
  };
}

/**
 * Deterministic readiness score. The model supplies only the `why` strings via
 * `input.reasons`; every point here is computed locally so attaching an image
 * moves the bar with no round trip.
 */
export function readinessScore(input: ReadinessInput): ReadinessResult {
  const checks: ReadinessCheck[] = [];
  let points = 0;

  if (input.descriptionLength >= DESCRIPTION_CLEAR_CHARS) {
    points += READINESS_WEIGHTS.description;
    checks.push({ ok: true, label: 'Clear description' });
  } else if (input.descriptionLength >= DESCRIPTION_THIN_CHARS) {
    points += READINESS_WEIGHTS.descriptionThin;
    checks.push({
      ok: false,
      label: 'Description is thin',
      why: input.reasons?.desc ?? 'A sentence or two more would help — what did you expect instead?',
      act: 'Add more',
      target: 'description',
    });
  } else {
    checks.push({
      ok: false,
      label: 'Description is very short',
      why: input.reasons?.desc ?? 'A sentence or two more would help — what did you expect instead?',
      act: 'Add more',
      target: 'description',
    });
  }

  if (input.contextLength > CONTEXT_MIN_CHARS) {
    points += READINESS_WEIGHTS.context;
    checks.push({ ok: true, label: input.kind === 'bug' ? 'Steps to reproduce' : 'Rationale given' });
  } else {
    checks.push({
      ok: false,
      label: input.kind === 'bug' ? 'No steps to reproduce' : 'No rationale',
      why:
        input.reasons?.ctx ??
        (input.kind === 'bug'
          ? 'Without steps, this can only be guessed at.'
          : 'Saying why you want it shapes how it gets built.'),
      act: 'Add them',
      target: 'context',
    });
  }

  if (input.attachmentCount > 0) {
    points += READINESS_WEIGHTS.attachment;
    checks.push({
      ok: true,
      label: `${input.attachmentCount} image${input.attachmentCount > 1 ? 's' : ''} attached`,
    });
  } else {
    checks.push({
      ok: false,
      label: 'No image',
      why: input.reasons?.image ?? 'A screenshot usually makes this kind of report much faster to act on.',
      act: 'Attach one',
      target: 'attachments',
    });
  }

  if (input.includeDiagnostics) {
    points += READINESS_WEIGHTS.diagnostics;
    checks.push({ ok: true, label: 'Versions and recent errors attached' });
  } else {
    checks.push({
      ok: false,
      label: 'Diagnostics removed',
      why: 'Versions make most bugs far quicker to place.',
      act: 'Put back',
      target: 'diagnostics',
    });
  }

  return { score: Math.round((points / READINESS_MAX) * 100), checks };
}
