// GENERATED by video/build-timeline.mjs from video/script.yaml — do not edit by hand.
// Regenerate with `npm run timeline` in video/ (see video/README.md). Pure data: no imports,
// so it is safe in both tsconfigs and the mcp-server build.

/** Caption cues for media/onboarding/getting-started.mp4, in seconds. */
export const GETTING_STARTED_CUES: { start: number; end: number; text: string }[] = [
  { start: 0.35, end: 3.723, text: 'Your dbt project, as a diagram, in about a minute.' },
  { start: 3.773, end: 6.26, text: 'No AI, and nothing to configure.' },
  { start: 6.71, end: 10.63, text: 'Install ERD Studio, and open your dbt project.' },
  { start: 10.68, end: 12.994, text: 'The Get started guide opens by itself.' },
  { start: 13.444, end: 17.184, text: 'Click Draw from dbt, and pick a folder, like your marts.' },
  { start: 19.244, end: 24.162, text: 'It reads your models and their relationship tests, and lays out the diagram for you.' },
  { start: 25.244, end: 26.957, text: 'That\'s your Logical design.' },
  { start: 27.007, end: 29.435, text: 'Click a table to see its columns and keys.' },
  { start: 29.485, end: 33.211, text: 'It\'s saved as plain files in your repo, next to your SQL.' },
  { start: 33.661, end: 36.968, text: 'Switch to Physical to see what dbt actually built.' },
  { start: 37.018, end: 40.424, text: 'Diff compares the two, and flags anywhere they disagree.' },
  { start: 40.874, end: 43.726, text: 'Want grain, keys and the why behind each table?' },
  { start: 43.776, end: 49.193, text: 'Click Set Up My AI Helper, then type /erd-studio-setup in your assistant.' },
  { start: 50.174, end: 53.673, text: 'No dbt project? Try the sample project.' },
  { start: 55.074, end: 60.12, text: 'ERD Studio is free. Install it, and draw your dbt project today.' },
];

/** The narration as plain text, one paragraph per scene, for the Welcome panel's Transcript. */
export const GETTING_STARTED_TRANSCRIPT: string = [
  'Your dbt project, as a diagram, in about a minute. No AI, and nothing to configure.',
  'Install ERD Studio, and open your dbt project. The Get started guide opens by itself.',
  'Click Draw from dbt, and pick a folder, like your marts.',
  'It reads your models and their relationship tests, and lays out the diagram for you.',
  'That\'s your Logical design. Click a table to see its columns and keys. It\'s saved as plain files in your repo, next to your SQL.',
  'Switch to Physical to see what dbt actually built. Diff compares the two, and flags anywhere they disagree.',
  'Want grain, keys and the why behind each table? Click Set Up My AI Helper, then type /erd-studio-setup in your assistant.',
  'No dbt project? Try the sample project.',
  'ERD Studio is free. Install it, and draw your dbt project today.',
].join('\n\n');
