import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';
import { parse as yamlParse } from 'yaml';

import { SelectorsService } from '../../src/services/selectorsService';
import type { DomainService } from '../../src/services/domainService';

interface FakeDomain {
  domain: string;
  layer: string;
  filePath: string;
  models: string[];
}

function fakeDomainService(domains: FakeDomain[]): DomainService {
  return {
    listDomains: () =>
      domains.map((d) => ({ domain: d.domain, layer: d.layer, filePath: d.filePath })),
    getDomain: (filePath: string) => {
      const found = domains.find((d) => d.filePath === filePath);
      if (!found) { throw new Error(`Not found: ${filePath}`); }
      return {
        schemaVersion: 5,
        domain: found.domain,
        layer: found.layer,
        description: '',
        logical: {
          models: found.models.map((name) => ({ name, columns: [] })),
          relationships: [],
        },
        viewConfig: {},
      };
    },
  } as unknown as DomainService;
}

interface ParsedSelectors {
  selectors: Array<{
    name: string;
    description: string;
    definition: { union: Array<{ method: string; value: string }> };
  }>;
}

function readSelectors(workspaceRoot: string): ParsedSelectors {
  const content = fs.readFileSync(path.join(workspaceRoot, 'selectors.yml'), 'utf-8');
  return yamlParse(content) as ParsedSelectors;
}

describe('SelectorsService', () => {
  let tmpDir: string;

  beforeEach(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'selectors-svc-'));
  });

  afterEach(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true });
  });

  it('emits one selector per non-empty domain with snake_case names', () => {
    const svc = new SelectorsService(
      fakeDomainService([
        {
          domain: 'customer-360',
          layer: 'silver',
          filePath: '/dummy/silver/customer-360.json',
          models: ['dim_customer', 'fct_orders'],
        },
        {
          domain: 'reporting',
          layer: 'gold',
          filePath: '/dummy/gold/reporting.json',
          models: ['fct_revenue'],
        },
      ]),
      tmpDir,
      'erd-studio',
    );

    const result = svc.regenerate();
    expect(result.selectorsWritten).toBe(2);
    expect(result.modelsReferenced).toBe(3);

    const parsed = readSelectors(tmpDir);
    const names = parsed.selectors.map((s) => s.name);
    expect(names).toEqual(['domain_gold_reporting', 'domain_silver_customer_360']);

    const customer = parsed.selectors.find((s) => s.name === 'domain_silver_customer_360')!;
    expect(customer.definition.union).toEqual([
      { method: 'fqn', value: 'dim_customer' },
      { method: 'fqn', value: 'fct_orders' },
    ]);
  });

  it('references a conformed dimension in every domain that owns it', () => {
    const svc = new SelectorsService(
      fakeDomainService([
        {
          domain: 'customer-360',
          layer: 'silver',
          filePath: '/dummy/silver/customer-360.json',
          models: ['dim_customer', 'fct_orders'],
        },
        {
          domain: 'finance',
          layer: 'silver',
          filePath: '/dummy/silver/finance.json',
          models: ['dim_customer', 'fct_invoice'],
        },
      ]),
      tmpDir,
      'erd-studio',
    );

    svc.regenerate();
    const parsed = readSelectors(tmpDir);

    const customer = parsed.selectors.find((s) => s.name === 'domain_silver_customer_360')!;
    const finance = parsed.selectors.find((s) => s.name === 'domain_silver_finance')!;
    const customerHas = customer.definition.union.some((m) => m.value === 'dim_customer');
    const financeHas = finance.definition.union.some((m) => m.value === 'dim_customer');
    expect(customerHas).toBe(true);
    expect(financeHas).toBe(true);
  });

  it('skips empty domains entirely', () => {
    const svc = new SelectorsService(
      fakeDomainService([
        {
          domain: 'placeholder',
          layer: 'silver',
          filePath: '/dummy/silver/placeholder.json',
          models: [],
        },
        {
          domain: 'real',
          layer: 'silver',
          filePath: '/dummy/silver/real.json',
          models: ['dim_real'],
        },
      ]),
      tmpDir,
      'erd-studio',
    );

    const result = svc.regenerate();
    expect(result.selectorsWritten).toBe(1);
    const parsed = readSelectors(tmpDir);
    expect(parsed.selectors.map((s) => s.name)).toEqual(['domain_silver_real']);
  });

  it('writes a header marking the file as autogenerated', () => {
    const svc = new SelectorsService(
      fakeDomainService([
        { domain: 'd', layer: 'silver', filePath: '/x/silver/d.json', models: ['m1'] },
      ]),
      tmpDir,
      'erd-studio',
    );
    svc.regenerate();
    const raw = fs.readFileSync(path.join(tmpDir, 'selectors.yml'), 'utf-8');
    expect(raw.startsWith('# AUTOGENERATED')).toBe(true);
  });

  it('sanitizes non-alphanumeric characters in layer and domain names', () => {
    // Layer IDs come from user-editable layers.json and may contain dots,
    // spaces, etc. dbt selector names must be identifier-safe.
    const svc = new SelectorsService(
      fakeDomainService([
        {
          domain: 'customer 360',
          layer: 'v2.0',
          filePath: '/dummy/v2.0/customer 360.json',
          models: ['dim_customer'],
        },
      ]),
      tmpDir,
      'erd-studio',
    );
    svc.regenerate();

    const parsed = readSelectors(tmpDir);
    expect(parsed.selectors[0].name).toBe('domain_v2_0_customer_360');
  });

  it('overwrites an existing selectors.yml on regenerate (no stale selectors)', () => {
    fs.writeFileSync(
      path.join(tmpDir, 'selectors.yml'),
      'selectors:\n  - name: domain_silver_old\n    definition:\n      union:\n        - method: fqn\n          value: ghost_model\n',
      'utf-8',
    );

    const svc = new SelectorsService(
      fakeDomainService([
        { domain: 'new', layer: 'silver', filePath: '/x/silver/new.json', models: ['dim_new'] },
      ]),
      tmpDir,
      'erd-studio',
    );
    svc.regenerate();

    const parsed = readSelectors(tmpDir);
    const names = parsed.selectors.map((s) => s.name);
    expect(names).toContain('domain_silver_new');
    expect(names).not.toContain('domain_silver_old');
  });
});
